### ISSUE TITLE
[FEATURE] QA

### ISSUE THREAD

**Issue by hwanheejung** [DDD-Community/DDD-11-Sonny-Polabo-FE#46]
### 기능 설명
QA 반영

## TODO
- [x] 보드 공유하기 복사 안됨 
- [x] 한줄메시지 처음부터 placeholder로
- [x] safari 사진 치우침 현상
- [x] 보드 공유하기 모달에 close icon 추가
